### PR TITLE
ci: :construction_worker: optimize github action

### PR DESCRIPTION
**Pull request by onuralpszr**
You don't need to install pre-commit you should use "https://pre-commit.ci/" which I already setup in other PR once you setup formatter will work faster and work as a separate PR

### CODE REVIEW

**Comment by AdrianPayne** [comment]
@onuralpszr you removed the docker build and test jobs! 🤯

**Comment by onuralpszr** [comment]
> @onuralpszr you removed the docker build and test jobs! 🤯

I did not, I just made them cleaner

**Comment by onuralpszr** [comment]
> > @onuralpszr you removed the docker build and test jobs! 🤯
> 
> I did not, I just made them cleaner

I can still see compose and tests in there so all good. and passed.

**Comment by AdrianPayne** [comment]
As steps of the same job. With this we only have one check now instead of three:
image

**Comment by onuralpszr** [comment]
> As steps of the same job. With this we only have one check now instead of three: image

That is normal, instead of splitting "actions" which means new machine and pull the codes and etc. this is a proper way. I am not running pull code multiple times, so what you asking is visual but for function sake it is a waste

**Comment by onuralpszr** [comment]
@AdrianPayne  I finish this as well. And as I said we want to one fresh env and pull the code and finish tasks. That is it.

**Comment by AdrianPayne** [comment]
@onuralpszr I get your point, however I think it is faster for debugging to run the 3 checks at the same time. It can be some waste of machine, but not too much.

**Comment by onuralpszr** [comment]
> @onuralpszr I get your point, however I think it is faster for debugging to run the 3 checks at the same time. It can be some waste of machine, but not too much.

You already checks under one pull but personally i don't see value to seperate or build docker every time. Because if install and test pass your docker %99 percent pass as well but you want to split at least separate files, up to you.

**Comment by AdrianPayne** [comment]
Let's try your way

**Pull request merged**
